# Server Configuration
server.port=8080
server.servlet.context-path=/

# Application Name
spring.application.name=api-sample

# JPA Configuration
# spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=validate
spring.sql.init.mode=never

# Database Configuration (PostgreSQL)
spring.datasource.url=jdbc:postgresql://${DB_HOST:postgres}:${DB_PORT:5432}/${DB_NAME:myapp_db}
spring.datasource.username=${DB_USER:postgres}
spring.datasource.password=${DB_PASSWORD:postgres}
spring.datasource.driverClassName=org.postgresql.Driver

# CORS Configuration
cors.allowed-origins=http://localhost:3000

# Logging
logging.level.root=INFO

