# Server Configuration
server.port=8080
server.servlet.context-path=/

# Application Name
spring.application.name=api-sample

# JPA Configuration
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.defer-datasource-initialization=true

# CORS Configuration
cors.allowed-origins=http://localhost:3000

# Logging
logging.level.root=INFO

